### ISSUE TITLE
Access to the whole filesystem

### ISSUE THREAD

**Issue by marmotton** [flathub/com.zettlr.Zettlr#13]
Hello,
It seems that this Flatpak can only access $HOME/Documents and /tmp.
I guess it would be reasonable to allow it access to the whole filesystem, e.g. to be able to use the $HOME/Nextcloud folder or some USB thumb drives in /media.

Cheers,

Ben

**Comment by Lunarequest** [comment]
There are major security implications to allowing full filesystem access and it would defeat sandboxing the application. If you do require it, you can use flatseal to modify permissions of the flatpak

**Comment by marmotton** [comment]
Thanks for your reply, I didn't know about Flatseal. I installed it and could add access to the Nextcloud folder I'm insterested in, great, thanks !
