### ISSUE TITLE
Lost all files in a newly created folder

### ISSUE THREAD

**Issue by fain182** [flathub/com.zettlr.Zettlr#14]
As I reported on https://github.com/Zettlr/Zettlr/issues/3725 there is an issue on creating folders in the home directory and saving files, if zettlr is installed as a flatpak.

**Comment by Lunarequest** [comment]
I've tried to reproduce this several times on a bunch of different systems but I'm not able to reproduce this issue. Could you provide some information on your host system, any changes you may have made with flatseal etc

**Comment by fain182** [comment]
The host is a fedora 36, i did nothing with flatseal.

I suppose this flatpak can access only to ~/Documents, right?
I had the problem when from zettlr I created a directory like `~/Blog` and tried to write in there.

Let me know if I can help you with some logs, or if you want a screencast of the bug...

Thanks!

**Comment by Lunarequest** [comment]
Okay that makes sense. The flatpak can only interact with ~/Documents. It can not create files any where else. This isn't an issue with the flatpak itself as it's intended behaviour.

**Comment by fain182** [comment]
[Peek 11-09-2022 13-57.webm](https://user-images.githubusercontent.com/5879/189526332-fdf209df-8e4f-4ef6-b90a-a58f4ccc7f70.webm)

Sorry, my explanation was not clear enough...
The problem is that it seems to create folder and files, without giving any error, but then all your work is lost.

**Comment by Lunarequest** [comment]
I'll see if i can write a patch for it upstream
