### ISSUE TITLE
Revert to 3.3.1

### ISSUE THREAD

**Issue by PunkPangolin** [flathub/com.zettlr.Zettlr#49]
3.4.0 includes a bug that removes workspaces and does not allow to re-add them. See [here](https://github.com/Zettlr/Zettlr/issues/5526) and [here](https://github.com/Zettlr/Zettlr/issues/5526).

I would suggest reverting #48 until this is fixed upstream.

**Comment by nathanlesage** [comment]
Such a decision should be made on the main repo, and not here. Furthermore, a fix is currently building and will soon be released. This is easier for all than pulling and re-doing.
