### ISSUE TITLE
Updates

### ISSUE THREAD

**Issue by dagdrommer** [flathub/com.zettlr.Zettlr#5]
Hey everyone,

I very much appreciate your work, providing a Zettlr flatpak. However, the current Zettlr-Flatpak still has the version of its initial flatpak release and updates from Zettlr/Pull request form the Flathub-Bot ignored.
I would love to see the latest Zettlr updates.

Many thanks in advance.

**Comment by nathanlesage** [comment]
I ignore them because I simply do not have the time to tend to them. I was suspecting that @Lunarequest was handling these …? Otherwise we might need another maintainer, someone who can do this.

**Comment by Lunarequest** [comment]
Sorry I've been writing my end of term uni exams. I didn't notice these. My bad

**Comment by dagdrommer** [comment]
Thanks for the quick response.

@Lunarequest that's completely understandable. I hope your exams went well. 👍🏻

**Comment by Lunarequest** [comment]
Also as an FYI since we use the appimage and simply repackage files the only thing we need to do is merge the prs to update them
